---
# Main tasks file for the mediapeers.ruby role

- name: Ensure make is installed (needed to install ruby_install)
  become: true
  apt:
    name: make
    state: present
    update_cache: yes

# Installs the ruby-install tool:
- import_tasks: ruby_install.yml

# Installs ruby itself (from source):
- import_tasks: ruby.yml
